// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB76Q3qurni4KZ0q_YKbYZnryPhjaurISg',
    appId: '1:609826742099:web:7e0f280698b8847f924ba6',
    messagingSenderId: '609826742099',
    projectId: 'frchat-6d424',
    authDomain: 'frchat-6d424.firebaseapp.com',
    storageBucket: 'frchat-6d424.appspot.com',
    measurementId: 'G-TD9WJRWCXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_wm4V-jyWCoznEG561gHM-BByHleGCE',
    appId: '1:609826742099:android:b37a9ae79451bc46924ba6',
    messagingSenderId: '609826742099',
    projectId: 'frchat-6d424',
    storageBucket: 'frchat-6d424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrIUoYdtWIOh7SwuNte_AWWZolyXuyP0',
    appId: '1:609826742099:ios:ccfa1d769b42c0d5924ba6',
    messagingSenderId: '609826742099',
    projectId: 'frchat-6d424',
    storageBucket: 'frchat-6d424.appspot.com',
    iosClientId: '609826742099-pefak4h2nukpu2p8cunnn9mcd81v38t3.apps.googleusercontent.com',
    iosBundleId: 'me.teejaay.frbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZrIUoYdtWIOh7SwuNte_AWWZolyXuyP0',
    appId: '1:609826742099:ios:ccfa1d769b42c0d5924ba6',
    messagingSenderId: '609826742099',
    projectId: 'frchat-6d424',
    storageBucket: 'frchat-6d424.appspot.com',
    iosClientId: '609826742099-pefak4h2nukpu2p8cunnn9mcd81v38t3.apps.googleusercontent.com',
    iosBundleId: 'me.teejaay.frbase',
  );
}
